#!/usr/bin/env bash
# Check if exactly one argument is passed
if [ "$#" -eq 1 ]; then
    # Ping the IP address 5 times
    ping -c 5 "$1"
else
    # Display usage message if no argument is passed
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
